# Generated by Django 3.1.3 on 2021-07-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210716_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
    ]
